
# lint this file
# go get github.com/woodpecker-ci/woodpecker/cmd/cli
# cli lint .woodpecker.yml

variables:
    - &dcape_img 'dcape-compose'
    - &build_plugin 'plugins/docker'
    - &golang_img 'golang:1.21-alpine3.18'

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      lfs: false
      tags: true

steps:

  build:
    image: *golang_img
    commands:
      - apk add --no-cache curl git make jq bash openssl
      - make test
      - make showonce-static
    when:
      - event: push

  publish-dryrun:
    image: *build_plugin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    settings:
      dry_run: true
      purge: true
      tags: ["devel"]
    when:
      - event: push

  # Build, save and run docker image.
  deploy:
    image: *dcape_img
    commands:
      - export APP_VERSION=$(git describe --tags --always)
      - export RELEASE=$(git describe --tags --abbrev=0 --always)
      - export ENFIST_BRANCH=$CI_REPO_DEFAULT_BRANCH
      - make .build
      - make .default-deploy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      - event: tag
        ref: refs/tags/v*
