# This file will be joined with docker-compose.app.yml from dcape
# See https://github.com/dopos/dcape

services:
  app:
    labels:
      - traefik.http.routers.${APP_TAG}.rule=Host(`${APP_SITE:?Must be set}`)
      - traefik.http.routers.${APP_TAG}.service=${APP_TAG}
      - traefik.http.services.${APP_TAG}.loadbalancer.server.port=${LISTEN}
      # # Uncomment this to have GRPC outside
      # - traefik.http.services.${APP_TAG}-grpc.loadbalancer.server.scheme=h2c
      # - traefik.http.services.${APP_TAG}-grpc.loadbalancer.server.port=${LISTEN_GRPC}
      # - traefik.http.routers.${APP_TAG}-grpc.rule=Host(`grpc.${APP_SITE}`)
      # - traefik.http.routers.${APP_TAG}-grpc.tls=${USE_TLS}
      # - traefik.http.routers.${APP_TAG}-grpc.tls.certresolver=default
      # - traefik.http.routers.${APP_TAG}-grpc.service=${APP_TAG}-grpc
    command:
      --as.my_url ${HTTP_PROTO}://${APP_SITE} --as.cookie_name showonce_token
    volumes:
      - ./static:/static
    environment:
      - LISTEN
      - LISTEN_GRPC
      - ROOT
      - LOG_DEBUG
      - LOG_FORMAT
      - LOG_TIME_FORMAT
      - LOG_DEST
      - AS_TYPE
      - AS_DO401
      - AS_HOST
      - AS_TEAM
      - AS_CLIENT_ID
      - AS_CLIENT_KEY
      - AS_COOKIE_SIGN_KEY
      - AS_COOKIE_CRYPT_KEY
      - AS_USER_HEADER

    build:
      context: .
      args:
        APP_VER: "${APP_VER:-}"
        APP: "${APP_NAME:-}"
