# custom app config
# overrides DCAPE/apps/drone/dcape-app/docker-compose.yml

version: '2'

services:
  app:
    command:
      --log.debug --as.my_url ${APP_PROTO}://${APP_SITE} --as.cookie_name showonce_token
    environment:
      - AS_TYPE
      - AS_HOST
      - AS_TEAM
      - AS_CLIENT_ID
      - AS_CLIENT_KEY
      - AS_COOKIE_SIGN_KEY
      - AS_COOKIE_CRYPT_KEY

    build:
      context: .
      args:
        APP_VER: "${APP_VER:-}"
        APP: "${APP_NAME:-}"
