version: '2.1'

services:

  app:
    command:
      --debug --as.my_url ${APP_PROTO}://${APP_SITE} --as.cookie_name showonce_token
    environment:
      - AS_TYPE
      - AS_HOST
      - AS_TEAM
      - AS_CLIENT_ID
      - AS_CLIENT_KEY
      - AS_COOKIE_SIGN_KEY
      - AS_COOKIE_CRYPT_KEY
    build:
      context: .
    networks:
      - lan

networks:
  lan:
    external:
      name: ${DCAPE_NET}
