name: GoTest

on:
  push:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Test
        run: go test -v -tags test ./...
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: go test -tags test -race -covermode=atomic -coverprofile=c.out . ./cmd/... ./storage/...
          prefix: "github.com/LeKovr/showonce"
          debug: true

